---
apiVersion: v1
kind: Namespace
metadata:
  name: fargate
---


apiVersion: v1
kind: Pod
apiVersion: v1
metadata:
  name: satish-dummy-pod
  namespace: fargate

spec:
  containers:
    - name: satish-dummy-pod
      image: ubuntu
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
  restartPolicy: Never